DROP TABLE IF EXISTS meal_dishes;
DROP TABLE IF EXISTS meals;
DROP TABLE IF EXISTS dishes;
DROP TABLE IF EXISTS users;

create TABLE dishes
(
    id                   BIGINT           NOT NULL,
    name                 VARCHAR(255),
    calories_per_serving DOUBLE PRECISION NOT NULL,
    proteins             DOUBLE PRECISION NOT NULL,
    fats                 DOUBLE PRECISION NOT NULL,
    carbohydrates        DOUBLE PRECISION NOT NULL,
    CONSTRAINT pk_dishes PRIMARY KEY (id)
);

create TABLE meal_dishes
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    meal_id  BIGINT,
    dish_id  BIGINT,
    quantity INTEGER                                 NOT NULL,
    CONSTRAINT pk_meal_dishes PRIMARY KEY (id)
);

create TABLE meals
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                  NOT NULL,
    date    date,
    time    time WITHOUT TIME ZONE,
    CONSTRAINT pk_meals PRIMARY KEY (id)
);

create TABLE users
(
    id                 BIGINT           NOT NULL,
    name               VARCHAR(255),
    gender             VARCHAR(255),
    email              VARCHAR(255),
    age                INTEGER          NOT NULL,
    weight             DOUBLE PRECISION NOT NULL,
    height             DOUBLE PRECISION NOT NULL,
    goal               VARCHAR(255),
    daily_calorie_norm DOUBLE PRECISION NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

alter table users
    add CONSTRAINT uc_users_email UNIQUE (email);

alter table meals
    add CONSTRAINT FK_MEALS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

alter table meal_dishes
    add CONSTRAINT FK_MEAL_DISHES_ON_DISH FOREIGN KEY (dish_id) REFERENCES dishes (id);

alter table meal_dishes
    add CONSTRAINT FK_MEAL_DISHES_ON_MEAL FOREIGN KEY (meal_id) REFERENCES meals (id);